apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vcentral
    version: v2
  name: vcentral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vcentral
  template:
    metadata:
      labels:
        app: vcentral
    spec:
      hostname: vcentral
      containers:
        - name: vcentral
          image: jkempf42/public-repo:v2-dev.vcentral
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: [ "-c", "while true; do sleep 600; done" ]
          volumeMounts:
            - mountPath: /home/volttron/db
              name: vcentral-db
      nodeSelector:
        kubernetes.io/hostname: k3s-central
      volumes:
        - name: vcentral-db
          persistentVolumeClaim:
            claimName: vcentral-claim
