apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: volttron-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vcentral-pv
  labels:
    type: vcentral-pv-storage
    app: vcentral
spec:
  capacity:
    storage: 500Mi
  storageClassName: volttron-local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/volttron/db
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k3s-central
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vcentral-claim
  labels:
    app: vcentral
spec:
  storageClassName: volttron-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
