apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bacnet
spec:
  config: '{
      "cniVersion": "0.4.0",
      "name": "bacnet",
      "type": "host-device",
      "device": "enp0s8",
      "ipam": {
        "type": "dhcp"
       }
    }'
