apiVersion: v1
kind: Service
metadata:
  labels:
    app: vbac
    version: v2
  name: vbac
spec:
  selector:
    app: vbac
  ports:
    - name: vbac
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: vip
      port: 22916
      protocol: TCP
      targetPort: 22916
  type: ClusterIP
